import { Club, Player } from "./types";

export const club: Club = {
  id: "club_001",
  name: "Sala Firenze",
  city: "Firenze",
  hallName: "Sala Firenze",
  reputation: 4,
  fans: 2340,
  balance: 248500,
  president: "Emiliano Rofi",
  coach: "Massimo Rossi",
  sponsor: "Gold Biliards",
};

export const players: Player[] = [
  {
    id: "1",
    firstName: "Luca",
    lastName: "Bianchi",
    age: 33,
    nationality: "Italia",
    category: "A",
    precision: 94,
    direct: 92,
    banks: 86,
    tactics: 90,
    mentality: 94,
    defense: 87,
    finishing: 91,
    creativity: 84,
    touch: 89,
    experience: 92,
    potential: 93,
    form: 9,
    morale: 8,
    marketValue: 185000,
    salary: 42000,
    contractYears: 3,
    overall: 91,
    talent: 88,
    specialTrait: "Ice Man",
    trait: "Ice Man",
  },
  {
    id: "2",
    firstName: "Andrea",
    lastName: "Conti",
    age: 28,
    nationality: "Italia",
    category: "B",
    precision: 84,
    direct: 81,
    banks: 88,
    tactics: 83,
    mentality: 84,
    defense: 82,
    finishing: 80,
    creativity: 86,
    touch: 85,
    experience: 76,
    potential: 88,
    form: 7,
    morale: 8,
    marketValue: 98000,
    salary: 26000,
    contractYears: 2,
    overall: 84,
    talent: 86,
    specialTrait: "Stratega",
    trait: "Stratega",
  },
  {
    id: "3",
    firstName: "Marco",
    lastName: "Rossi",
    age: 24,
    nationality: "Italia",
    category: "C",
    precision: 80,
    direct: 88,
    banks: 91,
    tactics: 80,
    mentality: 79,
    defense: 77,
    finishing: 84,
    creativity: 82,
    touch: 86,
    experience: 62,
    potential: 90,
    form: 10,
    morale: 10,
    marketValue: 72000,
    salary: 18000,
    contractYears: 4,
    overall: 79,
    talent: 91,
    specialTrait: "Talento Naturale",
    trait: "Talento Naturale",
  },
];